### ISSUE TITLE
The codes have some error

### ISSUE THREAD

**Issue by askkl** [ual-arm-ros-pkg/mvsim#1]
after installed ,i can't roslaunch the demo,then installed from sources,i met this
'CMakeFiles/mvsim_node.dir/mvsim_node_src/mvsim_node.cpp.o: In function `MVSimNode::MVSimVisitor_notifyROSWorldIsUpdated::visit(mvsim::WorldElementBase*)':
mvsim_node.cpp:(.text+0xe25): undefined reference to `mrpt_bridge::convert(mrpt::maps::COccupancyGridMap2D const&, nav_msgs::OccupancyGrid_<std::allocator<void> >&)'
CMakeFiles/mvsim_node.dir/mvsim_node_src/mvsim_node.cpp.o: In function `MVSimNode::MyWorld::onNewObservation(mvsim::VehicleBase const&, mrpt::obs::CObservation const*)':
mvsim_node.cpp:(.text+0x1457): undefined reference to `mrpt_bridge::convert(mrpt::obs::CObservation2DRangeScan const&, sensor_msgs::LaserScan_<std::allocator<void> >&, geometry_msgs::Pose_<std::allocator<void> >&)''

the codes are
 'void MVSimNode::MyWorld::onNewObservation(
	const mvsim::VehicleBase &veh,
#if MRPT_VERSION>=0x130
	const mrpt::obs::CObservation* obs
#else
	const mrpt::slam::CObservation* obs
#endif
	)'
but i don't know how to do

**Comment by jlblancoc** [comment]
What version of ROS are you using? Why you should not roslaunch the demo?

Also: try uninstalling ros-*-mrpt-bridge and also compiling mrpt_navigation from sources, since it seems that it is the problem. I'll mark this as closed unless it still fails, ok?
